/* Furni — shared site JavaScript */
const WHATSAPP_NUMBER='0000000000';
const PRODUCTS=[
{id:1,name:'Modular Sofa',price:32999,category:'living-room',material:'upholstery',img:'g.jpg'},
{id:2,name:'Solid Wood Dining Table',price:34999,category:'dining-room',material:'wood',img:'g.jpg'},
{id:3,name:'Minimal Lounge Chair',price:14999,category:'living-room',material:'wood',img:'g.jpg'},
{id:4,name:'Wooden Bed Frame',price:22999,category:'bedroom',material:'wood',img:'g.jpg'},
{id:5,name:'Study Desk',price:15499,category:'office',material:'wood',img:'g.jpg'},
{id:6,name:'Wardrobe',price:26999,category:'storage',material:'wood',img:'g.jpg'},
{id:7,name:'Wordy Desk',price:22999,category:'office',material:'metal',img:'g.jpg'},
{id:8,name:'Wooden Bed Frame II',price:24999,category:'bedroom',material:'wood',img:'g.jpg'}];
const getCart=()=>{try{return JSON.parse(localStorage.getItem('furni_cart'))||[]}catch{return[]}};
const saveCart=c=>localStorage.setItem('furni_cart',JSON.stringify(c));
const formatPrice=n=>'₹'+Number(n).toLocaleString('en-IN');
function updateCartBadge(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('.cart-badge').forEach(e=>{e.textContent=n;e.style.display=n?'flex':'none'})}
function addToCart(id,qty=1,extras={}){const p=PRODUCTS.find(x=>x.id===Number(id));if(!p)return;const c=getCart(),key=`${p.id}-${extras.color||''}-${extras.material||''}-${extras.fabric||''}`,old=c.find(x=>x.key===key);if(old)old.qty+=qty;else c.push({key,id:p.id,name:p.name,price:p.price,img:p.img,qty,...extras});saveCart(c);updateCartBadge();showToast(`"${p.name}" added to cart`,'check')}
function removeFromCart(key){saveCart(getCart().filter(x=>x.key!==key));updateCartBadge()}
function updateCartQty(key,d){const c=getCart(),i=c.find(x=>x.key===key);if(!i)return;i.qty=Math.max(1,i.qty+d);saveCart(c);return i.qty}
function getCartTotal(){return getCart().reduce((s,i)=>s+i.price*i.qty,0)}
function getWishlist(){try{const x=JSON.parse(localStorage.getItem('furni_wishlist'));return Array.isArray(x)?x.map(Number):[]}catch{return[]}}
function toggleWishlist(id){id=Number(id);const l=getWishlist(),i=l.indexOf(id);if(i>-1){l.splice(i,1);localStorage.setItem('furni_wishlist',JSON.stringify(l));return false}l.push(id);localStorage.setItem('furni_wishlist',JSON.stringify(l));return true}
function isWishlisted(id){return getWishlist().includes(Number(id))}
function showToast(message,icon='check'){let c=document.querySelector('.toast-container');if(!c){c=document.createElement('div');c.className='toast-container';document.body.appendChild(c)}const t=document.createElement('div');t.className='toast';t.innerHTML=`<span>${icon==='heart'?'♥':icon==='remove'?'×':'✓'}</span><span>${message}</span>`;c.appendChild(t);setTimeout(()=>t.remove(),2900)}
function openWhatsApp(message){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function initNavbar(){updateCartBadge();const h=document.querySelector('.hamburger'),m=document.querySelector('.mobile-nav');if(h&&m){h.addEventListener('click',()=>{const o=m.classList.toggle('open');h.setAttribute('aria-expanded',o)});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>m.classList.remove('open')))}const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a,.mobile-nav a').forEach(a=>{const p=(a.getAttribute('href')||'').split('?')[0].split('#')[0];if(p===path)a.classList.add('active')});const b=document.querySelector('.search-btn'),o=document.querySelector('.search-overlay'),cl=document.querySelector('.search-close'),inp=document.querySelector('.search-box input');if(b&&o){b.addEventListener('click',()=>{o.classList.add('open');setTimeout(()=>inp?.focus(),100)});cl?.addEventListener('click',()=>o.classList.remove('open'));o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')o.classList.remove('open');if(e.key==='Enter'&&document.activeElement===inp&&inp.value.trim())location.href=`shop.html?q=${encodeURIComponent(inp.value.trim())}`})}}
function buildProductCard(p){const w=isWishlisted(p.id);return `<article class="product-card" onclick="location.href='product.html?id=${p.id}'"><div class="product-img-wrap"><img src="images/${p.img}" alt="${p.name}" loading="lazy"><button class="wishlist-btn ${w?'active':''}" onclick="handleWishlist(event,${p.id},this)" aria-label="${w?'Remove from wishlist':'Add to wishlist'}"><svg viewBox="0 0 24 24" fill="${w?'currentColor':'none'}" stroke="currentColor"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg></button></div><div class="product-info"><p class="product-name">${p.name}</p><p class="product-price">${formatPrice(p.price)}</p></div></article>`}
function handleWishlist(e,id,b){e.stopPropagation();const a=toggleWishlist(id);b.classList.toggle('active',a);b.querySelector('svg')?.setAttribute('fill',a?'currentColor':'none');showToast(a?'Added to wishlist':'Removed from wishlist',a?'heart':'remove')}
function initShopPage(){const g=document.getElementById('products-grid');if(!g)return;let cat='all',mats=new Set(),max=102000;const q=new URLSearchParams(location.search),wanted=q.get('cat'),search=(q.get('q')||'').toLowerCase();if(wanted&&['all',...PRODUCTS.map(p=>p.category)].includes(wanted)){cat=wanted;document.querySelectorAll('.cat-filter-item').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat))}function render(){const a=PRODUCTS.filter(p=>(cat==='all'||p.category===cat)&&(!mats.size||mats.has(p.material))&&p.price<=max&&(!search||`${p.name} ${p.category} ${p.material}`.toLowerCase().includes(search)));const c=document.getElementById('products-count');if(c)c.innerHTML=`Showing <strong>${a.length}</strong> of <strong>${PRODUCTS.length}</strong> furniture`;g.innerHTML=a.length?a.map(buildProductCard).join(''):'<div style="grid-column:1/-1;text-align:center;padding:60px;color:var(--text-muted)">No products match your filters.</div>'}document.querySelectorAll('.cat-filter-item').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.cat-filter-item').forEach(i=>i.classList.remove('active'));x.classList.add('active');cat=x.dataset.cat;render()}));document.querySelectorAll('.check-item').forEach(x=>x.addEventListener('click',()=>{x.classList.toggle('checked');x.classList.contains('checked')?mats.add(x.dataset.material):mats.delete(x.dataset.material);render()}));const r=document.getElementById('price-range');r?.addEventListener('input',()=>{max=+r.value;const v=document.getElementById('price-max-val'),f=document.getElementById('range-fill');if(v)v.textContent=formatPrice(max);if(f)f.style.width=`${((max-5000)/97000)*100}%`;render()});render()}
function initProductPage(){const id=Number(new URLSearchParams(location.search).get('id')||3),p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[2];const set=(s,v)=>{const e=document.querySelector(s);if(e)e.textContent=v};set('.product-detail-name',p.name);set('.product-detail-price',formatPrice(p.price));set('.breadcrumb span:last-child',p.name);document.title=`${p.name} — Furni.`;const main=document.getElementById('main-product-img');if(main){main.src=`images/${p.img}`;main.alt=p.name}document.querySelectorAll('.thumb-item img').forEach(i=>{i.src=`images/${p.img}`;i.alt=p.name});document.querySelectorAll('.thumb-item').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.thumb-item').forEach(x=>x.classList.remove('active'));t.classList.add('active');if(main)main.src=t.querySelector('img').src}));document.querySelectorAll('.detail-color-swatch').forEach(s=>s.addEventListener('click',()=>{document.querySelectorAll('.detail-color-swatch').forEach(x=>x.classList.remove('active'));s.classList.add('active')}));document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{c.closest('.option-chips')?.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')}));const q=document.getElementById('qty-input');document.querySelector('.qty-inc')?.addEventListener('click',()=>q&&(q.value=Math.min(99,+q.value+1)));document.querySelector('.qty-dec')?.addEventListener('click',()=>q&&(q.value=Math.max(1,+q.value-1)));document.getElementById('add-to-cart-btn')?.addEventListener('click',()=>{const material=document.querySelectorAll('.option-chips')[0]?.querySelector('.chip.active')?.textContent.trim()||'',fabric=document.querySelectorAll('.option-chips')[1]?.querySelector('.chip.active')?.textContent.trim()||'',color=document.querySelector('.detail-color-swatch.active')?.dataset.color||'';addToCart(p.id,+(q?.value||1),{material,fabric,color})});const wb=document.getElementById('wishlist-btn');const sync=()=>{if(!wb)return;const on=isWishlisted(p.id);wb.classList.toggle('active',on);wb.innerHTML=`<svg viewBox="0 0 24 24" fill="${on?'currentColor':'none'}" stroke="currentColor" style="width:18px;height:18px"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>${on?'Wishlisted':'Add to Wishlist'}`};sync();wb?.addEventListener('click',()=>{const a=toggleWishlist(p.id);sync();showToast(a?'Added to wishlist':'Removed from wishlist',a?'heart':'remove')});const rg=document.getElementById('related-grid');if(rg)rg.innerHTML=PRODUCTS.filter(x=>x.id!==p.id).slice(0,4).map(buildProductCard).join('')}
function renderCart(){const c=getCart(),l=document.getElementById('cart-items'),empty=document.getElementById('cart-empty'),sum=document.getElementById('order-summary');if(!l)return;if(!c.length){l.innerHTML='';if(empty)empty.style.display='block';if(sum)sum.style.display='none';return}if(empty)empty.style.display='none';if(sum)sum.style.display='block';l.innerHTML=c.map(i=>`<div class="cart-item"><div class="cart-item-img"><img src="images/${i.img}" alt="${i.name}"></div><div class="cart-item-info"><p class="cart-item-name">${i.name}</p><p class="cart-item-meta">${[i.material?'Material: '+i.material:'',i.fabric?'Fabric: '+i.fabric:'',i.color?'Color: '+i.color:''].filter(Boolean).join(' · ')||'Standard configuration'}</p><div class="cart-item-qty"><button class="cart-qty-btn" onclick="changeCartQty('${i.key}',-1)">−</button><span class="cart-qty-val" id="qty-${i.key.replace(/[^a-z0-9]/gi,'_')}">${i.qty}</span><button class="cart-qty-btn" onclick="changeCartQty('${i.key}',1)">+</button></div></div><div class="cart-item-right"><p class="cart-item-price">${formatPrice(i.price*i.qty)}</p><button class="remove-btn" onclick="handleRemove('${i.key}')" aria-label="Remove item">×</button></div></div>`).join('');updateSummary()}
function changeCartQty(k,d){const q=updateCartQty(k,d),e=document.getElementById('qty-'+k.replace(/[^a-z0-9]/gi,'_'));if(e)e.textContent=q;updateSummary();updateCartBadge()}function handleRemove(k){removeFromCart(k);showToast('Item removed from cart','remove');renderCart()}
function updateSummary(){const c=getCart(),s=getCartTotal(),ship=s>=25000?0:499,e=id=>document.getElementById(id);if(e('summary-subtotal'))e('summary-subtotal').textContent=formatPrice(s);if(e('summary-shipping'))e('summary-shipping').textContent=ship?'₹499':'Free';if(e('summary-total'))e('summary-total').textContent=formatPrice(s+ship);if(e('cart-count'))e('cart-count').textContent=`(${c.reduce((n,i)=>n+i.qty,0)} items)`}
function checkoutCartViaWhatsApp(){const c=getCart();if(!c.length){showToast('Your cart is empty!','remove');return}const s=getCartTotal(),ship=s>=25000?0:499,items=c.map((i,n)=>`${n+1}. ${i.name}\n   Qty: ${i.qty}\n   Unit price: ${formatPrice(i.price)}\n   ${[i.material?'Material: '+i.material:'',i.fabric?'Fabric: '+i.fabric:'',i.color?'Color: '+i.color:''].filter(Boolean).join(', ')||'Standard configuration'}\n   Line total: ${formatPrice(i.price*i.qty)}`).join('\n\n');openWhatsApp(`Hello Furni., I would like to place an order.\n\nORDER DETAILS\n${items}\n\nSubtotal: ${formatPrice(s)}\nShipping: ${ship?'₹499':'Free'}\nTotal: ${formatPrice(s+ship)}\n\nPlease confirm availability, delivery details, and next steps.`)}
function customBuildWhatsApp(){const val=id=>document.getElementById(id)?.value.trim()||'Not provided';const message=`Hello Furni., I would like to request a custom furniture build.\n\nCUSTOM BUILD REQUEST\nName: ${val('cf-name')}\nEmail: ${val('cf-email')}\nPhone: ${val('cf-phone')}\nFurniture type: ${val('cf-type')}\nBudget: ${val('cf-budget')}\nTimeline: ${val('cf-timeline')}\nDescription: ${val('cf-desc')}\n\nPlease contact me with the quote and next steps.`;openWhatsApp(message)}
function initCartPage(){renderCart()}

document.addEventListener('submit',e=>{if(document.body.dataset.page==='custom-build'&&e.target.matches('form[onsubmit]')){e.preventDefault();e.stopImmediatePropagation();customBuildWhatsApp()}},true);
document.addEventListener('click',e=>{if(document.body.dataset.page==='cart'&&e.target.closest('button[onclick="handleCheckout()"]')){e.preventDefault();e.stopImmediatePropagation();checkoutCartViaWhatsApp()}},true);
document.addEventListener('DOMContentLoaded',()=>{initNavbar();const p=document.body.dataset.page;if(p==='shop')initShopPage();if(p==='product')initProductPage();if(p==='cart')initCartPage();});